### ISSUE TITLE
Support PTStemmer V2

### ISSUE THREAD

**Issue by michelole** [fracpete/ptstemmer-weka-package#1]
Version 2 provides several enhancements, including support for the Savoy stemmer. Consider adding support for it.

**Comment by fracpete** [comment]
Is version 2 of the stemmer available as Maven artifact from Maven Central (http://search.maven.org/)?

**Comment by michelole** [comment]
Could not find it, so I assume we would need to add the .jar as a library as it is currently done.

**Comment by fracpete** [comment]
Ok. Where can I obtain version 2 then?

**Comment by michelole** [comment]
It's in the original Google Code repository, section [Downloads](https://code.google.com/archive/p/ptstemmer/downloads).

Anyway, I went ahead and created pull request #2 with the necessary changes. Hope you are able to merge it! 😃

**Comment by fracpete** [comment]
Merged. :-)

**Comment by fracpete** [comment]
Instead of using a "supplied" jar in the maven build, I'm using the one available from Maven Central:
http://search.maven.org/#artifactdetails%7Ccom.github.fracpete%7Cptstemmer%7C2010.1.13%7Cjar
Released a new version of the Weka package:
https://github.com/fracpete/ptstemmer-weka-package/releases/tag/v2.0.0

**Comment by michelole** [comment]
That's great news! I'll start pointing to it on my projects then.

**Comment by fracpete** [comment]
Cool!
